"""Domain models — importing this module registers all models with Base.metadata."""
from app.models.analysis import (
    Competitor,
    GrowthOpportunity,
    IndustryData,
    MacroIndicator,
    MoatAssessment,
    growth_opportunity_evidence,
    moat_assessment_evidence,
)
from app.models.base import Base, TimestampMixin
from app.models.company import Classification, Company, Exchange, Security
from app.models.enums import (
    CatalystImpact,
    ClaimType,
    ClassificationLevel,
    CompetitorRelevance,
    ConfidenceLevel,
    CorporateActionType,
    DocumentType,
    EvidenceType,
    FindingType,
    GrowthCategory,
    GrowthMaturity,
    Likelihood,
    ManagementStatementCategory,
    ManagementStatementStatus,
    MetricUnit,
    MoatStrength,
    MoatType,
    PeriodType,
    ResearchRunStatus,
    RiskType,
    ScenarioType,
    ScoreDimension,
    SecurityType,
    Severity,
    SourceTier,
    SourceType,
    StatementType,
    ValuationModelType,
)
from app.models.evidence import (
    Claim,
    ClaimEvidence,
    DocumentVersion,
    Source,
    SourceReliability,
)
from app.models.financial import FinancialMetric, FinancialStatement, QuarterlyResult
from app.models.governance import (
    CorporateAction,
    CorporateAnnouncement,
    PromoterPledge,
    Shareholding,
)
from app.models.research import (
    Evidence,
    ManagementStatement,
    ResearchDocument,
    ResearchFinding,
    ResearchRun,
    research_finding_evidence,
)
from app.models.thesis import (
    Catalyst,
    CompanyScore,
    InvestmentThesis,
    Risk,
    ThesisVersion,
    catalyst_evidence,
    company_score_evidence,
    risk_evidence,
)
from app.models.valuation import Scenario, ValuationModel

__all__ = [
    "Base",
    "TimestampMixin",
    # Enums
    "CatalystImpact",
    "ClaimType",
    "ClassificationLevel",
    "CompetitorRelevance",
    "ConfidenceLevel",
    "CorporateActionType",
    "DocumentType",
    "EvidenceType",
    "FindingType",
    "GrowthCategory",
    "GrowthMaturity",
    "Likelihood",
    "ManagementStatementCategory",
    "ManagementStatementStatus",
    "MetricUnit",
    "MoatStrength",
    "MoatType",
    "PeriodType",
    "ResearchRunStatus",
    "RiskType",
    "ScenarioType",
    "ScoreDimension",
    "SecurityType",
    "Severity",
    "SourceTier",
    "SourceType",
    "StatementType",
    "ValuationModelType",
    # Company
    "Exchange",
    "Classification",
    "Company",
    "Security",
    # Financial
    "FinancialStatement",
    "FinancialMetric",
    "QuarterlyResult",
    # Governance
    "Shareholding",
    "PromoterPledge",
    "CorporateAction",
    "CorporateAnnouncement",
    # Research
    "ResearchDocument",
    "Evidence",
    "ManagementStatement",
    "ResearchRun",
    "ResearchFinding",
    "research_finding_evidence",
    # Evidence subsystem
    "Source",
    "DocumentVersion",
    "Claim",
    "ClaimEvidence",
    "SourceReliability",
    # Analysis
    "MoatAssessment",
    "moat_assessment_evidence",
    "GrowthOpportunity",
    "growth_opportunity_evidence",
    "Competitor",
    "IndustryData",
    "MacroIndicator",
    # Valuation
    "ValuationModel",
    "Scenario",
    # Thesis
    "InvestmentThesis",
    "ThesisVersion",
    "Risk",
    "risk_evidence",
    "Catalyst",
    "catalyst_evidence",
    "CompanyScore",
    "company_score_evidence",
]
